"""
Teleportation-based QDS protocol primitives.

This module coordinates the quantum simulation layer for the
signature-generation workflow.

It does not perform signature verification or security decisions.
"""

from __future__ import annotations

import hashlib

from ..quantum.measurements.evidence import QuantumEvidence
from ..quantum.states.state_utils import ComplexVector
from ..quantum.teleportation.protocol import teleport


PROTOCOL_VERSION = "qds-v1"


def compute_message_digest(message: str) -> str:
    """
    Compute a deterministic identifier for the signed message.
    """
    return hashlib.sha256(
        message.encode("utf-8")
    ).hexdigest()


def execute_protocol(
    *,
    message: str,
    input_state: ComplexVector,
    seed: int | None = None,
) -> tuple[str, QuantumEvidence]:
    """
    Execute the quantum portion of the QDS signing workflow.

    Returns:
        message_digest:
            Deterministic digest of the message.

        quantum_evidence:
            Evidence generated by the teleportation protocol.
    """

    message_digest = compute_message_digest(message)

    quantum_evidence = teleport(
        unknown_state=input_state,
        seed=seed,
    )

    return message_digest, quantum_evidence