"""
Domain model for security alerts.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class AlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


@dataclass(frozen=True)
class SecurityAlert:
    """Security alert generated by the detection pipeline."""

    alert_id: str
    verification_id: str

    threat_type: str
    severity: AlertSeverity

    title: str
    description: str

    status: AlertStatus = AlertStatus.OPEN

    evidence: tuple[dict[str, Any], ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)